/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function countTokens(text: string): number
export declare function createDiff(original: string, modified: string): string
export declare function applyPatch(content: string, search: string, replace: string): string
export declare function compactContext(text: string, maxTokens: number): string
